function:
  _target_: scripts.methods.ours_static
  _recursive_: false
name: ours
k : ${eval:"${communication.encoder.output_size} * 192 / (225*225*3)"}

parameters:
  # Galore parameters
  update_frequency: 3
  energy_threshold: 0.9

  # Compression + knn 
  batch_compression_rate: 0.5
  tokens_compression_rate: 0.5
  kmeans_iterations: 10

  # Random_freeze
  freeze_probability : 0.2

svd_channel:
  _target_: scripts.communication.Gaussian_Noise_Analogic_Channel_with_SVD
  snr: ${hyperparameters.snr}
  update_frequency: ${..parameters.update_frequency}
  energy_threshold:  ${..parameters.energy_threshold}