model:
  _target_: methods.proposal.model
  compression: ${..parameters.compression}
  pooling: ${..parameters.pooling}
name: proposal
parameters:
  desired_compression: null
  token_compression: null
  batch_compression: null
  pooling: cls
#model:
#  _target_: methods.proposal.NameOfClass
#  compression: 0.2
#Use NameOfClass instead of "name: proposal" as before
