train:
  _target_: torchvision.datasets.Flowers102
  split: train
  transform:
    _target_: torchvision.transforms.Compose
    _recursive_: true
    transforms:
      - _target_: torchvision.transforms.RandomCrop
        size: 224
        padding: 24
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ToTensor
  root: ${core.dataset_path}
  download: false

test:
  _target_: torchvision.datasets.Flowers102
  split: val
  transform:
    _target_: torchvision.transforms.Compose
    _recursive_: true
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Resize
        size: [224, 224]
  root: ${core.dataset_path}
  download: false
  
name : flowers-102
num_classes : 102 
epochs : 100 
batch_size : 256