train:
  _target_: torchvision.datasets.Food101
  split: train
  transform:
    _target_: torchvision.transforms.Compose
    _recursive_: true
    transforms:
      - _target_: torchvision.transforms.RandAugment
        num_ops: 2
        magnitude: 9
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0
      - _target_: torchvision.transforms.Resize
        size: [224, 224]
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std:  [0.229, 0.224, 0.225]
  root: ${core.dataset_path}
  download: Yes

test:
  _target_: torchvision.datasets.Food101
  split: test
  transform:
    _target_: torchvision.transforms.Compose
    _recursive_: true
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [224, 224]
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
  root: ${core.dataset_path}
  download: Yes

name : food-101
num_classes : 101 
batch_size : 128
max_communication: 3000 # This is the number of batches sent to obtain convergence with the uncompressed method 