train:
  _target_: torchvision.datasets.Food101
  split: train
  transform:
    _target_: torchvision.transforms.Compose
    _recursive_: true
    transforms:
      - _target_: torchvision.transforms.RandomResizedCrop
        size: 224
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ToTensor
  root: ${core.dataset_path}
  download: Yes

test:
  _target_: torchvision.datasets.Food101
  split: test
  transform:
    _target_: torchvision.transforms.Compose
    _recursive_: true
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [224, 224]  # Resize to make sure the shortest side is 224
      - _target_: torchvision.transforms.CenterCrop
        size: 224  # Consistent cropping from center
      - _target_: torchvision.transforms.ToTensor
  root: ${core.dataset_path}
  download: Yes

name : food-101
num_classes : 101 
batch_size : 256