train:
  _target_: torchvision.datasets.Imagenette
  split: train
  transform:
    _target_: torchvision.transforms.Compose
    _recursive_: true
    transforms:
      - _target_: torchvision.transforms.RandAugment
        num_ops: 2
        magnitude: 9
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0
      - _target_: torchvision.transforms.Resize
        size: [224, 224]
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
  root: data/imagenette
  download: no
  size: 'full'
test:
  _target_: torchvision.datasets.Imagenette
  split: val
  transform:
    _target_: torchvision.transforms.Compose
    _recursive_: true
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [224, 224]
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
  root: data/imagenette
  download: no
  size: 'full'

name : imagenette

num_classes : 10
batch_size : 128
