channel:
  _target_: comm.communication.Identity
  is_channel: true

encoder:
  _target_: comm.communication.Identity
  is_channel: false

decoder:
  _target_: comm.communication.Identity
  is_channel: false

name: clean 