channel:
  _target_:  comm.communication.Gaussian_Noise_Analogic_Channel
  snr_range: 10

encoder:
  _target_: comm.communication.Encoder
  n_layers: 2
  normalize: true
  drop_last_activation: true
  output_size: 0.5

decoder:
  _target_: comm.communication.Decoder
  n_layers: 2
  normalize: true
  drop_last_activation: false

name: noisy_and_autoencoded