channel:
  _target_: scripts.communication.Gaussian_Noise_Analogic_Channel
  snr_range: ${hyperparameters.snr_range}

encoder:
  _target_: scripts.communication.Encoder
  n_layers: 2
  normalize: true
  drop_last_activation: true
  output_size: 0.5

decoder:
  _target_: scripts.communication.Decoder
  n_layers: 2
  normalize: true
  drop_last_activation: false
