channel:
  _target_: scripts.communication.Gaussian_Noise_Analogic_Channel
  snr: ${hyperparameters.snr}
  k: ${hyperparameters.max_symbols}

encoder:
  _target_: scripts.communication.Encoder
  n_layers: 2
  normalize: true
  drop_last_activation: true

decoder:
  _target_: scripts.communication.Decoder
  n_layers: 2
  normalize: true
  drop_last_activation: false
