# Default Configurations 
defaults:
  - comm: full_analogic_channel
  - dataset: flowers_102
  - model: deit_tiny_patch16_224
  - optimizer: adam
  - method : delta
  - _self_

# IDk if this needs to be fixed 
hyperparameters:
  snr:   10       # Sound to noise ratio 
  split_index : 3  # Where to split the network
  experiment_name : prova 
  

# Set roots for results, datasets and plots 
core:
  dataset_root: ./data
  results_path: ./results
  plots_path : ./plots

hydra:
  run:
    dir: ${core.results_path}/${hyperparameters.experiment_name}/${dataset.name}/${model.model_name}/${method.name}/snr=${hyperparameters.snr}

  job:
    chdir: No
    config:
      override_dirname:
        exclude_keys: ['comm', 'dataset', 'model', 'optimizer', 'schema','split_index', 'hyperparameters']
        kv_sep: '='
        item_sep: '__'

  job_logging:
    root:
      level: WARNING  

