# Default Configurations 
defaults:
  - communication: clean
  - dataset: food_101
  - model: deit_tiny_patch16_224
  - optimizer: adam
  - method : proposal
  - hydra: default
  - _self_

# Hyperparameters 
hyperparameters:
  split_index : 3  # Where to split the network
  experiment_name : prova  # Name of the experiment


# Set folders for results, datasets and plots 
core:
  dataset_path: ./data
  results_path: ./results
  plots_path : ./plots

# Set results folder name 
#hydra:
#  run:
#    dir: ${core.results_path}/${hyperparameters.experiment_name}/${dataset.name}/${model.model_name}/${method.name}/communication=${communication.name}/params=${method.parameters}
##    dir: test
#
#  job:
#    chdir: No
#    config:
#      override_dirname:
#        exclude_keys: ['comm', 'dataset', 'model', 'optimizer', 'schema','split_index', 'hyperparameters']
#        kv_sep: '='
#        item_sep: '__'
#
#  job_logging:
#    root:
#      level: WARNING

