# Default Configurations 
defaults:
  - comm: just_channel
  - dataset: flowers_102
  - model: deit_tiny_patch16_224
  - optimizer: adam
  - schema : default
  - _self_

hyperparameters:
  snr:   100       # Sound to noise ratio 
  split_index : 3  # Where to split the network 

# Set roots for results and dataset 
core:
  dataset_root: ./data
  results_path: ./results

hydra:
  run:
    dir: ${core.results_path}/${hyperparameters.snr}

  job:
    chdir: No
    config:
      override_dirname:
        exclude_keys: ['comm', 'dataset', 'model', 'optimizer', 'schema','split_index', 'hyperparameters']
        kv_sep: '='
        item_sep: '__'


